# 当代码推动到 main 分支时，执行当前工作流程
# 更多配置信息: https://docs.github.com/cn/actions/getting-started-with-github-actions
name: deploy serverless scf
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
jobs:
 deploy:
  name: deploy serverless scf
  runs-on: ubuntu-latest
  steps:
     - name: clone local repository
       uses: actions/checkout@v2
     - name: 安装 node.js
       uses: actions/setup-node@v3.0.0 
       with: 
            node-version: "14.X"
     - name: 安装 yarn
       run: npm install yarn
     - name: 安装依赖
       run: yarn
     - name: build
       run: npm build
     - name: 部署到服务器
       uses: appleboy/scp-action@master
       with:
    #需要部署的文件地址
            source: 'build/*'
    # SSH address  服务器地址
            host: ${{ secrets.REMOTE_HOST }}
    # Remote dir path  服务器下部署文件存放路径
            target: ${{ secrets.REMOTE_PATH }}
    # SSH Port  服务器端口
            port: 22
    # SSH User name   用户名
            username: ${{ secrets.USER_NAME }}
    # SSH User password  用户密码
            password: ${{ secrets.PASSWORD }}
    # key  密匙
            key: ${{ secrets.SSH_KEY }}
