# 当代码推动到 main 分支时，执行当前工作流程
# 更多配置信息: https://docs.github.com/cn/actions/getting-started-with-github-actions
name: deploy serverless scf
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
jobs:
 deploy:
  name: deploy serverless scf
  runs-on: ubuntu-latest
  steps:
     - name: clone local repository
       uses: actions/checkout@v2
     - name: 安装 node.js
       uses: actions/setup-node@v3.0.0 
       with: 
            node-version: "14.X"
     - name: 安装 yarn
       run: npm install yarn
     - name: 安装依赖
       run: yarn
     - name: build
       run: npm build
     - name: deploy serverless
       uses: woodyyan/tencent-serverless-action@main
       env: # 环境变量
         STAGE: dev #您的部署环境
         SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
         TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }} #您的腾讯云账号 sercret ID，请在Settings-Secrets中配置
         TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }} #您的腾讯云账号 sercret key，请在Settings-Secrets中配置
